services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: driveshare-sqlserver-1
    environment:
      SA_PASSWORD: "YourStrong!Password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong!Password", "-C", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: driveshare-zookeeper-1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: driveshare-kafka-1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  init-kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: driveshare-init-kafka-1
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      echo -e 'Waiting for Kafka to be ready...'
      cub kafka-ready -b kafka:9092 1 40
      
      echo -e 'Creating kafka topics...'
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic license-uploaded-topic --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic license-status-topic --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic booking-confirmed-topic --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic new-car-listing-topic --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic user-targeted-topic --replication-factor 1 --partitions 3
      
      echo -e 'Successfully created topics.'
      "

  userservice:
    build:
      context: .
      dockerfile: DriveShare.UserService/Dockerfile
    container_name: driveshare-userservice-1
    ports:
      - "5001:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
      init-kafka:
        condition: service_completed_successfully
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # تغيير اسم الداتا بيز لـ DriveShare_UserDb 👇
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=DriveShare_UserDb;User Id=sa;Password=YourStrong!Password;TrustServerCertificate=True;MultipleActiveResultSets=true;
      - Kafka__BootstrapServers=kafka:9092
      - Jwt__Secret=ThisIsAVeryLongAndSecureSecretKeyForDriveShareProject2026ByEzzatSobhi
      - Jwt__Issuer=DriveShare
      - Jwt__Audience=DriveShareUsers
    volumes:
      - ./DriveShare.UserService/wwwroot/uploads:/app/wwwroot/uploads

  rentalservice:
    build:
      context: .
      dockerfile: DriveShare.RentalService/Dockerfile
    container_name: driveshare-rentalservice-1
    ports:
      - "5002:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
      init-kafka:
        condition: service_completed_successfully
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # تغيير اسم الداتا بيز لـ DriveShare_RentalDb 👇
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=DriveShare_RentalDb;User Id=sa;Password=YourStrong!Password;TrustServerCertificate=True;MultipleActiveResultSets=true;
      - Kafka__BootstrapServers=kafka:9092
      - Jwt__Secret=ThisIsAVeryLongAndSecureSecretKeyForDriveShareProject2026ByEzzatSobhi
      - Jwt__Issuer=DriveShare
      - Jwt__Audience=DriveShareUsers

  notificationservice:
    build:
      context: .
      dockerfile: DriveShare.NotificationService/Dockerfile
    container_name: driveshare-notificationservice-1
    ports:
      - "5003:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
      init-kafka:
        condition: service_completed_successfully
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # ضفنا بيانات الداتا بيز هنا برضه باسم منفصل 👇
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=DriveShare_NotificationDb;User Id=sa;Password=YourStrong!Password;TrustServerCertificate=True;MultipleActiveResultSets=true;
      - Kafka__BootstrapServers=kafka:9092
      - Jwt__Secret=ThisIsAVeryLongAndSecureSecretKeyForDriveShareProject2026ByEzzatSobhi
      - Jwt__Issuer=DriveShare
      - Jwt__Audience=DriveShareUsers

  frontend:
    build:
      context: ./driveshare-frontend
      dockerfile: Dockerfile
    container_name: driveshare-frontend-1
    ports:
      - "3002:80"
    depends_on:
      - userservice
      - rentalservice
      - notificationservice

networks:
  default:
    name: driveshare-network